image: golang:latest

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - ./bin/server

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

deploy:
  stage: deploy
  script:
    - make deploy
  environment: production
